Refugio/Refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include ('usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    
    url(r'^reset/password_reset$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, 
        name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, 
        {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)\$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, 
        name="password_reset_confirm"),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, 
        name="password_reset_complete"),
]

Refugio/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from mascota.views import index_mascota,listado, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', login_required(index_mascota), name='index_mascota'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    url(r'^listado$', listado, name='listado'),
]

Refugio/mascota/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from adopcion.models import Persona

# Create your models here.
class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)

	def __unicode__(self):
		return '{}'.format(self.nombre)

class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rexcate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna)

Refugio/mascota/forms.py
from django import forms

from mascota.models import Mascota

class MascotaForm(forms.ModelForm):
	class Meta:
		model=Mascota

		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rexcate',
			'persona',
			'vacuna',
		]
		labels ={
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad_aproximada': 'Edad Aproximada' ,
			'fecha_rexcate': 'Fecha de rescate',
			'persona': 'Adoptante',
			'vacuna': 'Vacunas',
		}
		widgets ={
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'sexo': forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rexcate': forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			'vacuna': forms.CheckboxSelectMultiple(),
		}

Refugio/mascota/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from mascota.forms import MascotaForm
from mascota.models import Mascota

# Create your views here.

def listado(request):
	lista = serializers.serialize('json', Mascota.objects.all(), fields=['nombre','sexo','edad_aproximada'])
	return HttpResponse(lista, content_type='application/json')

def index_mascota(request):
	#return HttpResponse("Index de Mascota")
	return render(request, 'mascota/index_mascota.html')

#****************************************
#*****Vistas  Basadas en Funciones*******
#****************************************	
"""def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()

	return render(request, 'mascota/mascota_form.html', {'form':form})
"""

#****************************************
#*****Listas  Basadas en Funciones*******
#****************************************
"""def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = { 'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)

"""
#****************************************
#*****Edicion  Basadas en Funciones******
#****************************************
"""def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html',{'form':form})
"""

#****************************************
#****Eliminar  Basadas en Funciones******
#****************************************
"""def mascota_delete(request,id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html',{'mascota':mascota})
"""

#****************************************
#*****Vistas  Basadas en Classes*******
#****************************************
class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
	paginate_by = 3

#****************************************
#*****Vistas  Basadas en Classes*******
#****************************************
class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

#****************************************
#*****Edicion  Basadas en Classes******
#****************************************
class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

#****************************************
#*****Eliminar  Basadas en Classes******
#****************************************

class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

Refugio/templates/mascota/index_mascota.html
{% extends 'base/base.html' %} 
{% load staticfiles %}
<!--> Para sobreescribir los bloques del archivo base </!-->


{% block tittle %} 
	Mascota
{% endblock %}


{% block content %} 
	<h2>Contenido de Mascota</h2>
{% endblock %}

Refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %} 
{% load staticfiles %}

{% block tittle %} 
	Mascota Eliminar
{% endblock %}

{% block style %} 
	<link rel="stylesheet" href="{% static 'css/estilos_mascota_delete.css' %}">
{% endblock %}

{% block content %} 
<form method='post'>
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
	<!-- {{ form.nombre }}-->
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class="btn btn-primary" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>	
{% endblock %}

Refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %} 
{% load staticfiles %}

{% block tittle %} 
	Mascota Nuevo
{% endblock %}



{% block content %} 
<form method='post'>
	{% csrf_token %}
	{{form.as_p}}
	<!-- {{ form.nombre }}-->
	<button type="submit">Guardar</button>
</form>	
{% endblock %}

Refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}


{% block content %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha de Rescate</td>
			<td>Adoptante</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td>{{ mascota.id }}</td>
			<td>{{ mascota.nombre }}</td>
			<td>{{ mascota.sexo }}</td>
			<td>{{ mascota.edad_aproximada }}</td>
			<td>{{ mascota.fecha_rexcate }}</td>
			<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>No hay registros de mascotas</h1>

		{% endif %}
	</tbody>
</table>
<div class="col-md-4 col-md-offset-4">
		<ul class="pager">
			<li class="previous">
				{% if page_obj.has_previous %}
				<a href="?page={{ page_obj.previous_page_number }}">&larr; Anterior</a>
				{% endif %}
			</li>
			<li class="next">
				{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}">Siguiente &rarr; </a>
				{% endif %}
			</li>
		</ul>
</div>
{% endblock %}