Refugio/Refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include ('usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    
    url(r'^reset/password_reset$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, 
        name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, 
        {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)\$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, 
        name="password_reset_confirm"),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, 
        name="password_reset_complete"),
]

Refugio/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
	url(r'^index$', login_required(index_adopcion)),
	url(r'^solicitud/listar$', login_required(SolicitudList.as_view()), name='solicitud_listar'),
	url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
	url(r'^solicitud/editar/(?P<pk>\d+)/$', login_required(SolicitudUpdate.as_view()), name='solicitud_editar'),
	url(r'^solicitud/eliminar/(?P<pk>\d+)/$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

Refugio/adopcion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=12)
	email = models.EmailField()
	domicilio = models.TextField(default='C')

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)


class Solicitud(models.Model):
	persona = models.ForeignKey(Persona, null=True, blank=True)
	numero_mascotas = models.IntegerField()
	razones = models.TextField()

Refugio/adopcion/forms.py
from django import forms

from adopcion.models import Persona, Solicitud


class PersonaForm(forms.ModelForm):

	class Meta:
		model = Persona
		fields = [
			'nombre',
			'apellidos',
			'edad',
			'telefono',
			'email',
			'domicilio',
		]
		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
			'edad': 'Edad',
			'telefono': 'Telefono',
			'email': 'Correo Electronico',
			'domicilio': 'Domicilio',
		}
		widgets ={
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'edad': forms.TextInput(attrs={'class':'form-control'}),
			'telefono': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
			'domicilio': forms.Textarea(attrs={'class':'form-control'}),
		}

class SolicitudForm(forms.ModelForm):

	class Meta:
		model = Solicitud
		fields = [
			'numero_mascotas',
			'razones',
		]
		labels={
			'numero_mascotas': 'Numero de Mascotas',
			'razones': 'Razones para adoptar',
		}
		widgets={
			'numero_mascotas': forms.TextInput(attrs={'class':'form-control'}),
			'razones': forms.Textarea(attrs={'class':'form-control'}),
		}

Refugio/adopcion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


from adopcion.models import Persona, Solicitud
from adopcion.forms import PersonaForm, SolicitudForm


# Create your views here.
def index_adopcion(request):
	return HttpResponse("Pagina para Adopcion")

class SolicitudList(ListView):
	model = Solicitud 
	template_name = 'adopcion/solicitud_list.html'
	paginate_by = 3

class SolicitudCreate(CreateView):
	model = Solicitud
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')


	def get_context_data(self, **kwargs):
		context = super(SolicitudCreate, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		if 'form2' not in context:
			context['form2'] = self.second_form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		form2 = self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			solicitud = form.save(commit=False)
			solicitud.persona = form2.save()
			solicitud.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, form2=form2))


class SolicitudUpdate(UpdateView):
	model = Solicitud
	second_model = Persona
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudUpdate, self).get_context_data(**kwargs)
		pk = self.kwargs.get('pk',0)
		solicitud = self.model.objects.get(id=pk)
		persona = self.second_model.objects.get(id=solicitud.persona_id)
		if 'form' not in context:
			context['form'] = self.form_class()
		if 'form2' not in context:
			context['form2'] = self.second_form_class(instance=persona)
		context['id']=pk
		return context


	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		id_solicitud = kwargs['pk']
		solicitud = self.model.objects.get(id=id_solicitud)
		persona = self.second_model.objects.get(id=solicitud.persona_id)
		form = self.form_class(request.POST, instance=solicitud)
		form2 = self.second_form_class(request.POST, instance=persona)
		if form.is_valid() and form2.is_valid():
			form.save()
			form2.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(DeleteView):
	model = Solicitud
	template_name = 'adopcion/solicitud_delete.html'
	success_url = reverse_lazy('adopcion:solicitud_listar')

Refugio/templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %} 
{% load staticfiles %}

{% block tittle %} 
	Eliminar Solicitud
{% endblock %}


{% block content %} 
<form method='post'>
	{% csrf_token %}
	<h3>¿Desea eliminar la solicitud de {{ object.persona.nombre }} {{ object.persona.apellidos }}?</h3>
	<!-- {{ form.nombre }}-->
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class="btn btn-primary" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
</form>	
{% endblock %}

Refugio/templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %} 
{% load staticfiles %}

{% block tittle %} 
	Nueva Solicitud
{% endblock %}


{% block content %} 
<form method="post">
	{% csrf_token %}
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<div class="form-group">
					<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
					{{form2.nombre}}
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					<label for="{{form2.apellidos.name}}">{{form2.apellidos.label}}</label>
					{{form2.apellidos}}
				</div>
			</div>
			
		</div>
		<div class="row">
			<div class="col-md-8">
				<div class="col-sm-4">
					<div class="form-group">
						<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
						{{form2.edad}}
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
						{{form2.telefono}}
					</div>
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
						{{form.numero_mascotas}}
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="{{form2.email.name}}">{{form2.email.label}}</label>
					{{form2.email}}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<div class="form-group">
					<label for="{{form2.domicilio.name}}">{{form2.domicilio.label}}</label>
					{{form2.domicilio}}
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					<label for="{{form.razones.name}}">{{form.razones.label}}</label>
					{{form.razones}}
				</div>
			</div>
		</div>
	</div>

<!--
	{{ form2.as_p }}
	{{ form.as_p }}
 -->
	<button type="submit">Guardar</button>
</form>
{% endblock %}

Refugio/templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %} 
{% load staticfiles %}

{% block tittle %} 
	Lista Adopcion
{% endblock %}

{% block content %} 
<table class="table table-bordered">
	<thead>
		<tr>
			<td>No. Solicitud</td>
			<td>Adoptante</td>
			<td>No. Mascota</td>
			<td>Razones</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for solicitud in object_list %}
		<tr>
			<td>{{ solicitud.id }}</td>
			<td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellido }}</td>
			<td>{{ solicitud.numero_mascotas }}</td>
			<td>{{ solicitud.razones }}</td>

			<td>
				<a href="{% url 'adopcion:solicitud_editar' solicitud.id %}" class="btn btn-primary">Editar</a>
				<a href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}" class="btn btn-danger">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registro de Solicitudes</h1>
		{% endif %}
	</tbody>
</table>

<div class="col-md-4 col-md-offset-4">
		<ul class="pager">
			<li class="previous">
				{% if page_obj.has_previous %}
				<a href="?page={{ page_obj.previous_page_number }}">&larr; Anterior</a>
				{% endif %}
			</li>
			<li class="next">
				{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}">Siguiente &rarr; </a>
				{% endif %}
			</li>
		</ul>
</div>
{% endblock %}