Refugio/Refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include ('mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include ('adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include ('usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    
    url(r'^reset/password_reset$', password_reset, 
        {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, 
        name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, 
        {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)\$', password_reset_confirm, 
        {'template_name':'registration/password_reset_confirm.html'}, 
        name="password_reset_confirm"),
    url(r'^reset/done$', password_reset_complete, 
        {'template_name':'registration/password_reset_complete.html'}, 
        name="password_reset_complete"),
]

Refugio/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
	url(r'^index$', login_required(index_adopcion)),
	url(r'^solicitud/listar$', login_required(SolicitudList.as_view()), name='solicitud_listar'),
	url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
	url(r'^solicitud/editar/(?P<pk>\d+)/$', login_required(SolicitudUpdate.as_view()), name='solicitud_editar'),
	url(r'^solicitud/eliminar/(?P<pk>\d+)/$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

Refugio/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from mascota.views import index_mascota,listado, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', login_required(index_mascota), name='index_mascota'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    url(r'^listado$', listado, name='listado'),
]

Refugio/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<title>{% block tittle %} Base {% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

		<style type="text/css">
  		body{
			padding-top: 80px;
		}
		</style>
		{% block style %} 

		{% endblock %}

	</head>
	<body>
		<div class="container">
			{% block navbar %} 
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
								<span class="sr-only">Menu</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>

							<a href="#" class="navbar-brand">Home</a>
						</div>
						<div class="collapse navbar-collapse" id="navbar-1">
						
							<!--**********************-->
							<!--******Mascota¨********-->
							<!--**********************-->
							<ul class="nav navbar-nav">
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Mascotas<span class="caret"></span>
									</a>
									<ul class="dropdown-menu" role="menu">
										<li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
										<li><a href="{% url 'mascota:mascota_listar' %}">Listar Mascota</a></li>
									</ul>
								</li>
							</ul>

							<!--**********************-->
							<!--******Adopciones******-->
							<!--**********************-->
							<ul class="nav navbar-nav">
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Adopciones<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a></li>
										<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar Solicitudes</a></li>
									</ul>
								</li>
							</ul>

							<!--**********************-->
							<!--*******Opciones*******-->
							<!--**********************-->
							<ul class="nav navbar-nav navbar-right">
								<li class="dropdown">
									<a href="http://www.maskota.com.mx/">MasKota</a>
								</li>

								<li class="dropdown">
									<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button">Opciones<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'logout' %}">Salir</a></li>
									</ul>
								</li>
							</ul>
						</div>
				</div>
			</nav>
			{% endblock %}

			{% block content %} 
			<h3>Este es el contenido Base</h3>
			{% endblock %}

		</div>
		{% block footer %} 
		{% endblock %}

		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	</body>
</html>

Refugio/templates/base/header.html
<header>Hola_Mundo_Mascota</header>